[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.19.0"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
